config/routes.rb
# encoding: utf-8

LibraryToGo::Application.routes.draw do

  devise_for :users

  require 'sidekiq/web'
  require 'sidekiq/util'
  mount Sidekiq::Web => '/sidekiq'

  root :to => 'pages#home'

  match '/auth/:provider/callback' => 'authentications#create'

  namespace :api, :path => "api/v1" do
    scope :v1 do
      # TODO
    end
  end

  namespace :admin do
    match '/' => 'static#index'
    match 'home' => 'static#index'
    resources :users
    resources :pages
    resources :roles
    resources :items do
      resources :item_instances
    end
    resources :locations
    resources :organizations
    resources :people
    # TODO: payment integration
    #resources :purchases
    #resources :line_items
    #resources :payments
  end

  resources :items do
    resources :item_instances
    resources :circulations
  end

  resources :users do
    resources :addresses
    resources :circulations, only: [:index, :show, :destroy]
  end

  resources :locations do
    resources :addresses
    get 'map'
  end

  resources :organizations do
    resources :locations
    resources :circulations
    get 'map'
  end

  resources :people do
    resources :addresses
  end

  controller :pages do
    get '/legal' => :legal
    get '/about' => :about
    get '/privacy' => :privacy
    get '/help' => :help
    get '/support' => :support
    get '/faq' => :faq
    get '/:slug' => :show
    # Handles the case of testing the action itself
    #get :show if Rails.env.test?
  end

end

app/views/admin/pages/_form.html.slim
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :contents
    = f.text_area :contents
  .field
    = f.label :visible_at
    = f.datetime_select :visible_at
  .field
    = f.label :hidden_at
    = f.datetime_select :hidden_at
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :user
    = f.text_field :user
  .actions = f.submit 'Save'

app/views/admin/pages/edit.html.slim
h1 Editing page

== render 'form'

= link_to 'Show', @page
'|
= link_to 'Back', pages_path

app/views/admin/pages/index.html.slim
h1 Listing pages

table
  tr
    th Title
    th Slug
    th Contents
    th Visible at
    th Hidden at
    th State
    th User
    th
    th
    th

  - @pages.each do |page|
    tr
      td = page.title
      td = page.slug
      td = page.contents
      td = page.visible_at
      td = page.hidden_at
      td = page.state
      td = page.user
      td = link_to 'Show', page
      td = link_to 'Edit', edit_admin_page_path(page)
      td = link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Page', new_admin_page_path

app/views/admin/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/admin/pages/show.html.slim
p#notice = notice

p
  strong Title:
  = @page.title
p
  strong Slug:
  = @page.slug
p
  strong Contents:
  = @page.contents
p
  strong Visible at:
  = @page.visible_at
p
  strong Hidden at:
  = @page.hidden_at
p
  strong State:
  = @page.state
p
  strong User:
  = @page.user

= link_to 'Edit', edit_page_path(@page)
'|
= link_to 'Back', pages_path