config/routes.rb
# encoding: utf-8

LibraryToGo::Application.routes.draw do

  devise_for :users

  require 'sidekiq/web'
  require 'sidekiq/util'
  mount Sidekiq::Web => '/sidekiq'

  root :to => 'pages#home'

  match '/auth/:provider/callback' => 'authentications#create'

  namespace :api, :path => "api/v1" do
    scope :v1 do
      # TODO
    end
  end

  namespace :admin do
    match '/' => 'static#index'
    match 'home' => 'static#index'
    resources :users
    resources :pages
    resources :roles
    resources :items do
      resources :item_instances
    end
    resources :locations
    resources :organizations
    resources :people
    # TODO: payment integration
    #resources :purchases
    #resources :line_items
    #resources :payments
  end

  resources :items do
    resources :item_instances
    resources :circulations
  end

  resources :users do
    resources :addresses
    resources :circulations, only: [:index, :show, :destroy]
  end

  resources :locations do
    resources :addresses
    get 'map'
  end

  resources :organizations do
    resources :locations
    resources :circulations
    get 'map'
  end

  resources :people do
    resources :addresses
  end

  controller :pages do
    get '/legal' => :legal
    get '/about' => :about
    get '/privacy' => :privacy
    get '/help' => :help
    get '/support' => :support
    get '/faq' => :faq
    get '/:slug' => :show
    # Handles the case of testing the action itself
    #get :show if Rails.env.test?
  end

end

app/models/organization.rb
# encoding: utf-8

class Organization
  include Mongoid::Document
  include Mongoid::Paranoia

  field :name, type: String
  field :alt_names, type: Hash
  field :description, type: String
  field :state, type: String
  field :urls, type: Hash

  # TODO: embeds_many locations?
  has_many :locations,
            validate: false,
            autosave: false,
            dependent: :destroy

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.slim
= form_for @organization do |f|
  - if @organization.errors.any?
    #error_explanation
      h2 = "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      ul
        - @organization.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/organizations/edit.html.slim
h1 Editing organization

== render 'form'

= link_to 'Show', @organization
'|
= link_to 'Back', organizations_path

app/views/organizations/index.html.slim
h1 Listing organizations

table
  tr
    th
    th
    th

  - @organizations.each do |organization|
    tr
      td = link_to 'Show', organization
      td = link_to 'Edit', edit_organization_path(organization)
      td = link_to 'Destroy', organization, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.slim
h1 New organization

== render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.slim
p#notice = notice


= link_to 'Edit', edit_organization_path(@organization)
'|
= link_to 'Back', organizations_path